### ISSUE TITLE
Add to cssnext

### ISSUE THREAD

**Issue by ai** [7studio/postcss-color-rgb#1]
Thanks for plugin. You need to add it to postcss-cssnext plugin pack.

**Comment by 7studio** [comment]
I am annoyed because this plugin already exists and it was added to postcss-next on [nov 2016](https://github.com/MoOx/postcss-cssnext/commit/e2ae3b3c0f282a099fc2606b0655b2716cc0721e). But I didn't find it on [postcss.parts](http://postcss.parts/tag/color?searchTerm=rgb).
I will try the other [postcss-color-rgb ](https://github.com/dmarchena/postcss-color-rgb) plugin with my tests and I will consider participating in it.
